import reactLogo from "../public/assets/images/skills/react-js-logo.jpg";
import tsLogo from "../public/assets/images/skills/ts-logo.jpg";
import nextJsLogo from "../public/assets/images/skills/nextjs-logo.jpg";
import tailwindLogo from "../public/assets/images/skills/tailwind-logo.jpg";
import firebaseLogo from "../public/assets/images/skills/firebase-logo.jpg";
import javaLogo from "../public/assets/images/skills/java-logo.jpg";
import jsLogo from "../public/assets/images/skills/javascript-logo.jpg";
import springbootLogo from "../public/assets/images/skills/springboot-logo.jpg";
import postgresqlLogo from "../public/assets/images/skills/postgresql-logo.jpg";
import mongodbLogo from "../public/assets/images/skills/mongodb-logo.jpg";
import rabbitmqLogo from "../public/assets/images/skills/rabbitmq-logo.jpg";
import scssLogo from "../public/assets/images/skills/scss-logo.jpg";
import jasperLogo from "../public/assets/images/skills/jasper-logo.jpg";
import materialUiLogo from "../public/assets/images/skills/mui-logo.jpg";
import htmlLogo from "../public/assets/images/skills/html-logo.jpg";
import cssLogo from "../public/assets/images/skills/css-logo.jpg";
import bootstrapLogo from "../public/assets/images/skills/bootstrap-logo.jpg";

export const REACT_LOGO = reactLogo;
export const TS_LOGO = tsLogo;
export const NEXTJS_LOGO = nextJsLogo;
export const TAILWIND_LOGO = tailwindLogo;
export const FIREBASE_LOGO = firebaseLogo;
export const JAVA_LOGO = javaLogo;
export const JS_LOGO = jsLogo;
export const SPRING_BOOT_LOGO = springbootLogo;
export const POSTGRESQL_LOGO = postgresqlLogo;
export const MONGODB_LOGO = mongodbLogo;
export const RABBITMQ_LOGO = rabbitmqLogo;
export const SCSS_LOGO = scssLogo;
export const JASPER_LOGO = jasperLogo;
export const MATERIAL_UI_LOGO = materialUiLogo;
export const HTML_LOGO = htmlLogo;
export const CSS_LOGO = cssLogo;
export const BOOTSTRAP_LOOG = bootstrapLogo;
